<?php
declare(strict_types=1);

require_once __DIR__ . '/../../../includes/auth.php';
require_once __DIR__ . '/../../../includes/db_connect.php';
require_once __DIR__ . '/../../../includes/helpers.php';
require_once __DIR__ . '/functions.php';

require_role('Admin', 'Operatore', 'Manager');
$pageTitle = 'Dettaglio pratica ANPR';

$praticaId = (int) ($_GET['id'] ?? 0);
if ($praticaId <= 0) {
    add_flash('warning', 'Pratica non valida.');
    header('Location: index.php');
    exit;
}

$pratica = anpr_fetch_pratica($pdo, $praticaId);
if (!$pratica) {
    add_flash('warning', 'Pratica non trovata.');
    header('Location: index.php');
    exit;
}

$csrfToken = csrf_token();
$hasCertificate = !empty($pratica['certificato_path']);
$customerEmail = trim((string) ($pratica['cliente_email'] ?? ''));
$hasDelega = !empty($pratica['delega_path']);
$signatureStatus = (string) ($pratica['delega_firma_status'] ?? 'non_inviata');
$signatureExpired = anpr_signature_is_expired($pratica);
$signatureAttempts = (int) ($pratica['delega_firma_attempts'] ?? 0);
$delegaAutoGenerated = !empty($pratica['delega_generata_auto']);
$canAutoGenerateDelega = anpr_can_generate_delega($pratica);

require_once __DIR__ . '/../../../includes/header.php';
require_once __DIR__ . '/../../../includes/sidebar.php';
?>
<div class="flex-grow-1 d-flex flex-column min-vh-100">
    <?php require_once __DIR__ . '/../../../includes/topbar.php'; ?>
    <main class="content-wrapper">
        <div class="page-toolbar mb-4">
            <div>
                <h1 class="h3 mb-0">Pratica <?php echo sanitize_output($pratica['pratica_code'] ?? ''); ?></h1>
                <p class="text-muted mb-0">Dettaglio anagrafico e lavorazione.</p>
            </div>
            <div class="toolbar-actions d-flex flex-wrap gap-2">
                <a class="btn btn-outline-warning" href="https://www.anagrafenazionale.interno.it/servizi-al-cittadino/" target="_blank" rel="noopener">
                    <i class="fa-solid fa-up-right-from-square me-2"></i>Portale ANPR
                </a>
                <a class="btn btn-outline-warning" href="index.php"><i class="fa-solid fa-arrow-left me-2"></i>Indietro</a>
                <a class="btn btn-outline-warning" href="edit_request.php?id=<?php echo $praticaId; ?>"><i class="fa-solid fa-pen me-2"></i>Modifica</a>
                <a class="btn btn-outline-warning" href="upload_certificate.php?id=<?php echo $praticaId; ?>"><i class="fa-solid fa-file-arrow-up me-2"></i>Certificato</a>
            </div>
        </div>
        <div class="row g-4">
            <div class="col-lg-7">
                <div class="card ag-card">
                    <div class="card-header bg-transparent border-0">
                        <h2 class="h5 mb-0">Informazioni pratica</h2>
                    </div>
                    <div class="card-body">
                        <dl class="row mb-0">
                            <dt class="col-sm-4">Codice</dt>
                            <dd class="col-sm-8"><?php echo sanitize_output($pratica['pratica_code'] ?? ''); ?></dd>

                            <dt class="col-sm-4">Cliente</dt>
                            <dd class="col-sm-8">
                                <?php
                                    $displayName = trim(($pratica['ragione_sociale'] ?? '') !== ''
                                        ? $pratica['ragione_sociale']
                                        : trim(($pratica['cognome'] ?? '') . ' ' . ($pratica['nome'] ?? '')));
                                    echo $displayName !== '' ? sanitize_output($displayName) : '<span class="text-muted">N/D</span>';
                                ?>
                            </dd>

                            <dt class="col-sm-4">Tipologia</dt>
                            <dd class="col-sm-8"><?php echo sanitize_output($pratica['tipo_pratica'] ?? ''); ?></dd>

                            <dt class="col-sm-4">Stato pratica</dt>
                            <dd class="col-sm-8"><span class="badge ag-badge text-uppercase"><?php echo sanitize_output($pratica['stato'] ?? ''); ?></span></dd>

                            <dt class="col-sm-4">Operatore</dt>
                            <dd class="col-sm-8"><?php echo !empty($pratica['operatore_username']) ? sanitize_output($pratica['operatore_username']) : '<span class="text-muted">N/D</span>'; ?></dd>

                            <dt class="col-sm-4">Creato il</dt>
                            <dd class="col-sm-8"><?php echo sanitize_output(format_datetime_locale($pratica['created_at'] ?? '')); ?></dd>

                            <dt class="col-sm-4">Aggiornato il</dt>
                            <dd class="col-sm-8"><?php echo sanitize_output(format_datetime_locale($pratica['updated_at'] ?? '')); ?></dd>
                        </dl>
                        <div class="mt-3">
                            <h3 class="h6 text-uppercase text-muted">Note interne</h3>
                            <p class="mb-0"><?php echo $pratica['note_interne'] ? nl2br(sanitize_output($pratica['note_interne'])) : '<span class="text-muted">Nessuna nota</span>'; ?></p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-5">
                <div class="card ag-card">
                    <div class="card-header bg-transparent border-0 d-flex justify-content-between align-items-center">
                        <h2 class="h5 mb-0">Certificato</h2>
                        <?php if (!empty($pratica['certificato_path'])): ?>
                            <form method="post" action="upload_certificate.php?id=<?php echo $praticaId; ?>" data-confirm="Rimuovere il certificato archiviato?">
                                <input type="hidden" name="_token" value="<?php echo sanitize_output($csrfToken); ?>">
                                <input type="hidden" name="id" value="<?php echo $praticaId; ?>">
                                <input type="hidden" name="action" value="remove">
                                <button class="btn btn-sm btn-outline-warning" type="submit"><i class="fa-solid fa-trash"></i></button>
                            </form>
                        <?php endif; ?>
                    </div>
                    <div class="card-body">
                        <?php if (!empty($pratica['certificato_path'])): ?>
                            <p class="mb-2">Ultimo caricamento: <strong><?php echo sanitize_output(format_datetime_locale($pratica['certificato_caricato_at'] ?? '')); ?></strong></p>
                            <?php if (!empty($pratica['certificato_hash'])): ?>
                                <p class="mb-3">Hash SHA-256: <code><?php echo sanitize_output($pratica['certificato_hash']); ?></code></p>
                            <?php endif; ?>
                            <a class="btn btn-warning text-dark" href="<?php echo sanitize_output(base_url($pratica['certificato_path'])); ?>" target="_blank" rel="noopener"><i class="fa-solid fa-file-pdf me-2"></i>Scarica certificato</a>
                            <p class="text-muted mt-3 mb-0 small">Consigliato upload su storage di backup esterno dopo ogni emissione.</p>
                        <?php else: ?>
                            <p class="text-muted mb-2">Nessun certificato caricato.</p>
                            <a class="btn btn-outline-warning" href="upload_certificate.php?id=<?php echo $praticaId; ?>">Carica ora</a>
                        <?php endif; ?>
                    </div>
                </div>
                <div class="card ag-card mt-4">
                    <div class="card-header bg-transparent border-0">
                        <h2 class="h5 mb-0">Servizi operativi</h2>
                    </div>
                    <div class="card-body">
                        <div class="mb-4">
                            <div class="d-flex justify-content-between align-items-center mb-2">
                                <h3 class="h6 text-uppercase text-muted mb-0">Firma digitale delega</h3>
                                <?php
                                    $badgeClass = 'bg-secondary';
                                    $badgeLabel = 'Non iniziata';
                                    if ($signatureStatus === 'otp_inviato') {
                                        $badgeClass = $signatureExpired ? 'bg-danger' : 'bg-warning text-dark';
                                        $badgeLabel = $signatureExpired ? 'OTP scaduto' : 'OTP inviato';
                                    } elseif ($signatureStatus === 'firmata') {
                                        $badgeClass = 'bg-success';
                                        $badgeLabel = 'Firmata';
                                    } elseif ($signatureStatus === 'scaduta') {
                                        $badgeClass = 'bg-danger';
                                        $badgeLabel = 'Scaduta';
                                    }
                                ?>
                                <span class="badge <?php echo $badgeClass; ?>"><?php echo sanitize_output($badgeLabel); ?></span>
                            </div>
                            <?php if (!$hasDelega): ?>
                                <p class="text-muted small mb-0">
                                    Carica la delega per abilitare la firma digitale remota.
                                    <?php if ($canAutoGenerateDelega): ?>
                                        In alternativa usa il pulsante "Genera automaticamente" in fondo alla scheda.
                                    <?php endif; ?>
                                </p>
                            <?php else: ?>
                                <?php if ($signatureStatus === 'firmata'): ?>
                                    <p class="mb-1 small">Firmata il: <strong><?php echo sanitize_output(format_datetime_locale($pratica['delega_firma_verificata_il'] ?? '')); ?></strong></p>
                                    <p class="mb-2 small">Destinatario OTP: <?php echo sanitize_output($pratica['delega_firma_recipient'] ?? ''); ?></p>
                                    <form method="post" action="delega_signature.php" class="d-inline" data-confirm="Annullare lo stato di firma e richiedere una nuova sottoscrizione?">
                                        <input type="hidden" name="_token" value="<?php echo sanitize_output($csrfToken); ?>">
                                        <input type="hidden" name="pratica_id" value="<?php echo $praticaId; ?>">
                                        <input type="hidden" name="action" value="reset">
                                        <button class="btn btn-outline-warning" type="submit"><i class="fa-solid fa-rotate-left me-2"></i>Reimposta firma</button>
                                    </form>
                                <?php else: ?>
                                    <?php if ($signatureStatus === 'otp_inviato' && !$signatureExpired): ?>
                                        <p class="mb-1 small">OTP inviato a: <?php echo sanitize_output($pratica['delega_firma_recipient'] ?? ''); ?></p>
                                        <p class="mb-2 small">Inviato il: <strong><?php echo sanitize_output(format_datetime_locale($pratica['delega_firma_inviata_il'] ?? '')); ?></strong></p>
                                        <?php
                                            $remainingSeconds = null;
                                            if (!empty($pratica['delega_firma_inviata_il'])) {
                                                try {
                                                    $sentAt = new DateTimeImmutable($pratica['delega_firma_inviata_il']);
                                                    $remainingSeconds = max(0, ($sentAt->getTimestamp() + ANPR_SIGNATURE_OTP_TTL) - time());
                                                } catch (Throwable $exception) {
                                                    $remainingSeconds = null;
                                                }
                                            }
                                            if ($remainingSeconds !== null) {
                                                $remainingMinutes = (int) ceil($remainingSeconds / 60);
                                                echo '<p class="text-muted small">Codice valido ancora per circa ' . $remainingMinutes . ' min.</p>';
                                            }
                                        ?>
                                        <?php if ($signatureAttempts > 0): ?>
                                            <p class="text-muted small">Tentativi effettuati: <?php echo $signatureAttempts; ?> / <?php echo ANPR_SIGNATURE_MAX_ATTEMPTS; ?></p>
                                        <?php endif; ?>
                                        <form method="post" action="delega_signature.php" class="row g-2 align-items-end mb-2">
                                            <input type="hidden" name="_token" value="<?php echo sanitize_output($csrfToken); ?>">
                                            <input type="hidden" name="pratica_id" value="<?php echo $praticaId; ?>">
                                            <input type="hidden" name="action" value="verify">
                                            <div class="col-sm-6">
                                                <label class="form-label" for="otp-code">Codice OTP</label>
                                                <input class="form-control" type="text" id="otp-code" name="otp" maxlength="6" pattern="[0-9]{6}" inputmode="numeric" required>
                                                <small class="text-muted">Inserisci il codice comunicato dal cliente.</small>
                                            </div>
                                            <div class="col-sm-6 d-flex justify-content-end">
                                                <button class="btn btn-warning text-dark" type="submit"><i class="fa-solid fa-check me-2"></i>Conferma firma</button>
                                            </div>
                                        </form>
                                        <div class="d-flex flex-wrap gap-2 justify-content-end">
                                            <form method="post" action="delega_signature.php" data-confirm="Inviare nuovamente l'OTP al cliente?">
                                                <input type="hidden" name="_token" value="<?php echo sanitize_output($csrfToken); ?>">
                                                <input type="hidden" name="pratica_id" value="<?php echo $praticaId; ?>">
                                                <input type="hidden" name="action" value="send">
                                                <input type="hidden" name="recipient" value="<?php echo sanitize_output($pratica['delega_firma_recipient'] ?? $customerEmail); ?>">
                                                <button class="btn btn-outline-warning" type="submit"><i class="fa-solid fa-paper-plane me-2"></i>Reinvia OTP</button>
                                            </form>
                                            <form method="post" action="delega_signature.php" data-confirm="Annullare l'OTP attivo?">
                                                <input type="hidden" name="_token" value="<?php echo sanitize_output($csrfToken); ?>">
                                                <input type="hidden" name="pratica_id" value="<?php echo $praticaId; ?>">
                                                <input type="hidden" name="action" value="reset">
                                                <button class="btn btn-outline-warning" type="submit"><i class="fa-solid fa-rotate-left me-2"></i>Annulla OTP</button>
                                            </form>
                                        </div>
                                    <?php else: ?>
                                        <?php if ($signatureExpired || $signatureStatus === 'scaduta'): ?>
                                            <p class="text-muted small">L'OTP precedente è scaduto o il limite di tentativi è stato raggiunto. Invia nuovamente il codice.</p>
                                        <?php endif; ?>
                                        <form method="post" action="delega_signature.php" class="row g-2 align-items-end">
                                            <input type="hidden" name="_token" value="<?php echo sanitize_output($csrfToken); ?>">
                                            <input type="hidden" name="pratica_id" value="<?php echo $praticaId; ?>">
                                            <input type="hidden" name="action" value="send">
                                            <div class="col-sm-7">
                                                <label class="form-label" for="signature-email">Email destinatario OTP</label>
                                                <input class="form-control" type="email" id="signature-email" name="recipient" value="<?php echo sanitize_output($pratica['delega_firma_recipient'] ?? $customerEmail); ?>" required>
                                                <small class="text-muted">Invieremo un codice OTP gratuito al cliente.</small>
                                            </div>
                                            <div class="col-sm-5 d-flex justify-content-end">
                                                <button class="btn btn-warning text-dark" type="submit"><i class="fa-solid fa-paper-plane me-2"></i>Invia OTP</button>
                                            </div>
                                        </form>
                                    <?php endif; ?>
                                <?php endif; ?>
                            <?php endif; ?>
                        </div>
                        <div class="border-top pt-3">
                            <div class="d-flex justify-content-between align-items-center mb-2">
                                <h3 class="h6 text-uppercase text-muted mb-0">Verifica identità SPID</h3>
                                <?php if (!empty($pratica['spid_verificato_at'])): ?>
                                    <span class="badge bg-success">Verificato</span>
                                <?php else: ?>
                                    <span class="badge bg-secondary">Da verificare</span>
                                <?php endif; ?>
                            </div>
                            <?php if (!empty($pratica['spid_verificato_at'])): ?>
                                <p class="mb-1 small">Ultima verifica: <strong><?php echo sanitize_output(format_datetime_locale($pratica['spid_verificato_at'])); ?></strong></p>
                                <p class="mb-3 small">Operatore: <?php echo !empty($pratica['spid_operatore_username']) ? sanitize_output($pratica['spid_operatore_username']) : '<span class="text-muted">N/D</span>'; ?></p>
                                <form method="post" action="spid_verification.php" class="d-flex gap-2" data-confirm="Annullare la verifica SPID?">
                                    <input type="hidden" name="_token" value="<?php echo sanitize_output($csrfToken); ?>">
                                    <input type="hidden" name="pratica_id" value="<?php echo $praticaId; ?>">
                                    <input type="hidden" name="action" value="reset">
                                    <button class="btn btn-outline-warning" type="submit"><i class="fa-solid fa-rotate-left me-2"></i>Annulla verifica</button>
                                </form>
                            <?php else: ?>
                                <p class="text-muted small mb-3">Registra la verifica SPID per certificare l&apos;identità del richiedente.</p>
                                <form method="post" action="spid_verification.php" class="d-flex gap-2">
                                    <input type="hidden" name="_token" value="<?php echo sanitize_output($csrfToken); ?>">
                                    <input type="hidden" name="pratica_id" value="<?php echo $praticaId; ?>">
                                    <input type="hidden" name="action" value="verify">
                                    <button class="btn btn-warning text-dark" type="submit"><i class="fa-solid fa-fingerprint me-2"></i>Segna come verificato</button>
                                </form>
                            <?php endif; ?>
                        </div>

                        <div class="border-top pt-3 mt-3">
                            <div class="d-flex justify-content-between align-items-center mb-2">
                                <h3 class="h6 text-uppercase text-muted mb-0">Invio al cliente</h3>
                                <?php if (!empty($pratica['certificato_inviato_at'])): ?>
                                    <span class="badge bg-success">Inviato</span>
                                <?php else: ?>
                                    <span class="badge bg-secondary">In attesa</span>
                                <?php endif; ?>
                            </div>
                            <?php if (!empty($pratica['certificato_inviato_at'])): ?>
                                <p class="mb-1 small">Inviato il: <strong><?php echo sanitize_output(format_datetime_locale($pratica['certificato_inviato_at'])); ?></strong></p>
                                <p class="mb-2 small">Canale: <?php echo sanitize_output(strtoupper($pratica['certificato_inviato_via'] ?? '')); ?> → <?php echo sanitize_output($pratica['certificato_inviato_destinatario'] ?? ''); ?></p>
                            <?php endif; ?>
                            <?php if ($hasCertificate && $customerEmail !== ''): ?>
                                <form method="post" action="send_certificate.php" class="row g-2" enctype="application/x-www-form-urlencoded">
                                    <input type="hidden" name="_token" value="<?php echo sanitize_output($csrfToken); ?>">
                                    <input type="hidden" name="pratica_id" value="<?php echo $praticaId; ?>">
                                    <div class="col-12">
                                        <label class="form-label" for="recipient-email">Destinatario</label>
                                        <input class="form-control" type="email" id="recipient-email" name="recipient" value="<?php echo sanitize_output($customerEmail); ?>" required>
                                    </div>
                                    <div class="col-12">
                                        <label class="form-label" for="channel">Canale</label>
                                        <select class="form-select" id="channel" name="channel">
                                            <option value="email" selected>Email</option>
                                            <option value="pec">PEC</option>
                                        </select>
                                    </div>
                                    <div class="col-12">
                                        <label class="form-label" for="message">Messaggio opzionale</label>
                                        <textarea class="form-control" id="message" name="message" rows="3" placeholder="Gentile cliente, in allegato il certificato richiesto."></textarea>
                                        <small class="text-muted">Il PDF viene linkato nel testo; per invio PEC allegalo manualmente se richiesto dal provider.</small>
                                    </div>
                                    <div class="col-12 d-flex justify-content-end">
                                        <button class="btn btn-warning text-dark" type="submit"><i class="fa-solid fa-paper-plane me-2"></i>Invia al cliente</button>
                                    </div>
                                </form>
                            <?php else: ?>
                                <p class="text-muted small mb-0">Per inviare il certificato serve caricarlo e avere l&apos;email del cliente.</p>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <div class="card ag-card mt-4">
                    <div class="card-header bg-transparent border-0">
                        <h2 class="h5 mb-0">Documentazione raccolta</h2>
                    </div>
                    <div class="card-body">
                        <div class="mb-4">
                            <h3 class="h6 text-uppercase text-muted">Delega firmata</h3>
                            <?php if (!empty($pratica['delega_path'])): ?>
                                <p class="mb-2">Ultimo caricamento: <strong><?php echo sanitize_output(format_datetime_locale($pratica['delega_caricato_at'] ?? '')); ?></strong></p>
                                <?php if ($delegaAutoGenerated): ?>
                                    <p class="mb-2"><span class="badge bg-warning text-dark">Generata automaticamente</span></p>
                                <?php endif; ?>
                                <?php if (!empty($pratica['delega_hash'])): ?>
                                    <p class="mb-3">Hash SHA-256: <code><?php echo sanitize_output($pratica['delega_hash']); ?></code></p>
                                <?php endif; ?>
                                <a class="btn btn-outline-warning" href="<?php echo sanitize_output(base_url($pratica['delega_path'])); ?>" target="_blank" rel="noopener">
                                    <i class="fa-solid fa-file-lines me-2"></i>Scarica delega
                                </a>
                                <?php if ($canAutoGenerateDelega): ?>
                                    <form method="post" action="generate_delega.php" class="d-inline-block" data-confirm="Rigenerare la delega automaticamente? Eventuali stati di firma verranno reimpostati.">
                                        <input type="hidden" name="_token" value="<?php echo sanitize_output($csrfToken); ?>">
                                        <input type="hidden" name="pratica_id" value="<?php echo $praticaId; ?>">
                                        <input type="hidden" name="action" value="generate">
                                        <button class="btn btn-warning text-dark ms-2" type="submit"><i class="fa-solid fa-file-circle-plus me-2"></i>Rigenera delega</button>
                                    </form>
                                <?php endif; ?>
                            <?php else: ?>
                                <p class="text-muted mb-0">Nessuna delega caricata.</p>
                                <?php if ($canAutoGenerateDelega): ?>
                                    <form method="post" action="generate_delega.php" class="mt-3 d-inline-block" data-confirm="Generare automaticamente la delega per questa pratica?">
                                        <input type="hidden" name="_token" value="<?php echo sanitize_output($csrfToken); ?>">
                                        <input type="hidden" name="pratica_id" value="<?php echo $praticaId; ?>">
                                        <input type="hidden" name="action" value="generate">
                                        <button class="btn btn-warning text-dark" type="submit"><i class="fa-solid fa-file-circle-plus me-2"></i>Genera automaticamente</button>
                                    </form>
                                <?php endif; ?>
                            <?php endif; ?>
                        </div>
                        <div>
                            <h3 class="h6 text-uppercase text-muted">Documento identità</h3>
                            <?php if (!empty($pratica['documento_path'])): ?>
                                <p class="mb-2">Ultimo caricamento: <strong><?php echo sanitize_output(format_datetime_locale($pratica['documento_caricato_at'] ?? '')); ?></strong></p>
                                <?php if (!empty($pratica['documento_hash'])): ?>
                                    <p class="mb-3">Hash SHA-256: <code><?php echo sanitize_output($pratica['documento_hash']); ?></code></p>
                                <?php endif; ?>
                                <a class="btn btn-outline-warning" href="<?php echo sanitize_output(base_url($pratica['documento_path'])); ?>" target="_blank" rel="noopener">
                                    <i class="fa-solid fa-id-card me-2"></i>Scarica documento
                                </a>
                            <?php else: ?>
                                <p class="text-muted mb-0">Nessun documento caricato.</p>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <div class="card ag-card mt-4">
                    <div class="card-header bg-transparent border-0">
                        <h2 class="h5 mb-0">Contatti cliente</h2>
                    </div>
                    <div class="card-body">
                        <p class="mb-1"><strong>Email:</strong> <?php echo !empty($pratica['cliente_email']) ? sanitize_output($pratica['cliente_email']) : '<span class="text-muted">N/D</span>'; ?></p>
                        <p class="mb-0"><strong>Telefono:</strong> <?php echo !empty($pratica['cliente_telefono']) ? sanitize_output($pratica['cliente_telefono']) : '<span class="text-muted">N/D</span>'; ?></p>
                    </div>
                </div>
            </div>
        </div>
    </main>
</div>
<?php require_once __DIR__ . '/../../../includes/footer.php'; ?>
