CREATE TABLE IF NOT EXISTS consulenze_fiscali (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    codice VARCHAR(40) NOT NULL UNIQUE,
    cliente_id INT UNSIGNED NULL,
    intestatario_nome VARCHAR(180) NOT NULL,
    codice_fiscale VARCHAR(20) NOT NULL,
    tipo_modello VARCHAR(10) NOT NULL,
    anno_riferimento SMALLINT UNSIGNED NOT NULL,
    periodo_riferimento VARCHAR(60) NULL,
    importo_totale DECIMAL(12,2) NOT NULL,
    numero_rate TINYINT UNSIGNED NOT NULL DEFAULT 1,
    frequenza_rate VARCHAR(20) NOT NULL DEFAULT 'unica',
    prima_scadenza DATE NOT NULL,
    stato VARCHAR(40) NOT NULL DEFAULT 'bozza',
    promemoria_scadenza DATE NULL,
    promemoria_inviato_at DATETIME NULL,
    note TEXT NULL,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_consulenze_cliente (cliente_id),
    INDEX idx_consulenze_stato (stato),
    INDEX idx_consulenze_scadenza (prima_scadenza),
    INDEX idx_consulenze_promemoria (promemoria_scadenza),
    CONSTRAINT fk_consulenze_cliente FOREIGN KEY (cliente_id) REFERENCES clienti(id) ON DELETE SET NULL,
    CONSTRAINT fk_consulenze_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_consulenze_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS consulenze_fiscali_rate (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    consulenza_id INT UNSIGNED NOT NULL,
    numero TINYINT UNSIGNED NOT NULL,
    importo DECIMAL(12,2) NOT NULL,
    scadenza DATE NOT NULL,
    stato VARCHAR(20) NOT NULL DEFAULT 'pending',
    pagato_il DATE NULL,
    note VARCHAR(255) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uniq_consulenze_rate (consulenza_id, numero),
    INDEX idx_consulenze_rate_scadenza (scadenza),
    INDEX idx_consulenze_rate_stato (stato),
    CONSTRAINT fk_consulenze_rate_consulenza FOREIGN KEY (consulenza_id) REFERENCES consulenze_fiscali(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS consulenze_fiscali_documenti (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    consulenza_id INT UNSIGNED NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(255) NOT NULL,
    mime_type VARCHAR(120) NOT NULL,
    file_size BIGINT UNSIGNED NOT NULL DEFAULT 0,
    signed TINYINT(1) NOT NULL DEFAULT 1,
    uploaded_by INT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_consulenze_documenti_consulenza (consulenza_id),
    CONSTRAINT fk_consulenze_documenti_consulenza FOREIGN KEY (consulenza_id) REFERENCES consulenze_fiscali(id) ON DELETE CASCADE,
    CONSTRAINT fk_consulenze_documenti_user FOREIGN KEY (uploaded_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
