CREATE TABLE IF NOT EXISTS cie_prenotazioni (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    prenotazione_code VARCHAR(40) NOT NULL UNIQUE,
    cliente_id INT UNSIGNED NULL,
    cittadino_nome VARCHAR(100) NOT NULL,
    cittadino_cognome VARCHAR(100) NOT NULL,
    cittadino_cf VARCHAR(16) NULL,
    cittadino_email VARCHAR(160) NULL,
    cittadino_telefono VARCHAR(40) NULL,
    data_nascita DATE NULL,
    luogo_nascita VARCHAR(150) NULL,
    residenza_indirizzo VARCHAR(200) NULL,
    residenza_cap VARCHAR(10) NULL,
    residenza_citta VARCHAR(120) NULL,
    residenza_provincia VARCHAR(5) NULL,
    comune_richiesta VARCHAR(150) NOT NULL,
    disponibilita_data DATE NULL,
    disponibilita_fascia VARCHAR(80) NULL,
    appuntamento_data DATE NULL,
    appuntamento_orario VARCHAR(20) NULL,
    appuntamento_numero VARCHAR(80) NULL,
    stato VARCHAR(32) NOT NULL DEFAULT 'nuova',
    documento_identita_path VARCHAR(255) NULL,
    documento_identita_nome VARCHAR(160) NULL,
    documento_identita_mime VARCHAR(80) NULL,
    foto_cittadino_path VARCHAR(255) NULL,
    foto_cittadino_nome VARCHAR(160) NULL,
    foto_cittadino_mime VARCHAR(80) NULL,
    ricevuta_path VARCHAR(255) NULL,
    ricevuta_nome VARCHAR(160) NULL,
    ricevuta_mime VARCHAR(80) NULL,
    note TEXT NULL,
    esito TEXT NULL,
    conferma_email_sent_at DATETIME NULL,
    reminder_email_sent_at DATETIME NULL,
    reminder_whatsapp_sent_at DATETIME NULL,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_cie_prenotazioni_stato (stato),
    INDEX idx_cie_prenotazioni_cliente (cliente_id),
    INDEX idx_cie_prenotazioni_codice (prenotazione_code),
    INDEX idx_cie_prenotazioni_created (created_at),
    FOREIGN KEY (cliente_id) REFERENCES clienti(id) ON DELETE SET NULL,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cie_prenotazioni_notifiche (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    prenotazione_id INT UNSIGNED NOT NULL,
    channel VARCHAR(40) NOT NULL,
    message_subject VARCHAR(180) NOT NULL,
    notes TEXT NULL,
    sent_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_cie_notifiche_prenotazione (prenotazione_id),
    INDEX idx_cie_notifiche_channel (channel),
    FOREIGN KEY (prenotazione_id) REFERENCES cie_prenotazioni(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
