CREATE TABLE IF NOT EXISTS pickup_customer_brt_shipments (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    customer_id INT NOT NULL,
    brt_shipment_id INT UNSIGNED NOT NULL,
    numeric_sender_reference BIGINT UNSIGNED NOT NULL,
    alphanumeric_sender_reference VARCHAR(80) NOT NULL,
    parcel_id VARCHAR(60) NULL,
    tracking_by_parcel_id VARCHAR(60) NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'created',
    label_path VARCHAR(255) NULL,
    parcels SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    total_weight_kg DECIMAL(10,3) NOT NULL DEFAULT 0,
    total_volume_m3 DECIMAL(10,3) NOT NULL DEFAULT 0,
    destination_name VARCHAR(180) NOT NULL,
    destination_address VARCHAR(255) NOT NULL,
    destination_zip VARCHAR(20) NOT NULL,
    destination_city VARCHAR(150) NOT NULL,
    destination_province VARCHAR(10) NULL,
    destination_country VARCHAR(4) NOT NULL,
    metadata LONGTEXT NULL,
    last_synced_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_pickup_brt_customer_reference (customer_id, numeric_sender_reference),
    KEY idx_pickup_brt_customer (customer_id),
    KEY idx_pickup_brt_status (status),
    CONSTRAINT fk_pickup_brt_customer FOREIGN KEY (customer_id) REFERENCES pickup_customers(id) ON DELETE CASCADE,
    CONSTRAINT fk_pickup_brt_shipment FOREIGN KEY (brt_shipment_id) REFERENCES brt_shipments(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
