CREATE TABLE IF NOT EXISTS `pickup_portal_payments` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `public_reference` CHAR(26) NOT NULL,
    `customer_id` INT UNSIGNED NOT NULL,
    `status` VARCHAR(20) NOT NULL DEFAULT 'pending',
    `amount_cents` INT UNSIGNED NOT NULL,
    `currency` CHAR(3) NOT NULL,
    `tier_index` INT UNSIGNED NOT NULL,
    `tier_label` VARCHAR(100) NOT NULL,
    `stripe_session_id` VARCHAR(255) DEFAULT NULL,
    `stripe_payment_intent_id` VARCHAR(255) DEFAULT NULL,
    `shipment_payload` LONGTEXT NOT NULL,
    `shipment_portal_id` INT UNSIGNED DEFAULT NULL,
    `shipment_core_id` INT UNSIGNED DEFAULT NULL,
    `error_message` TEXT DEFAULT NULL,
    `paid_at` DATETIME DEFAULT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uniq_portal_payments_reference` (`public_reference`),
    UNIQUE KEY `uniq_portal_payments_session` (`stripe_session_id`),
    KEY `idx_portal_payments_status_customer` (`status`, `customer_id`),
    KEY `idx_portal_payments_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
