CREATE TABLE IF NOT EXISTS caf_patronato_pratiche (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    pratica_code VARCHAR(40) NOT NULL UNIQUE,
    tipo_pratica ENUM('CAF','Patronato') NOT NULL DEFAULT 'CAF',
    servizio VARCHAR(120) NULL,
    nominativo VARCHAR(160) NOT NULL,
    codice_fiscale VARCHAR(16) NULL,
    telefono VARCHAR(40) NULL,
    email VARCHAR(150) NULL,
    cliente_id INT UNSIGNED NULL,
    appuntamento_id INT UNSIGNED NULL,
    stato VARCHAR(40) NOT NULL DEFAULT 'Da lavorare',
    priorita TINYINT UNSIGNED NOT NULL DEFAULT 0,
    scadenza_at DATE NULL,
    note_interne TEXT NULL,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    closed_at DATETIME NULL,
    INDEX idx_caf_patronato_cliente (cliente_id),
    INDEX idx_caf_patronato_stato (stato),
    INDEX idx_caf_patronato_tipo (tipo_pratica),
    INDEX idx_caf_patronato_appuntamento (appuntamento_id),
    INDEX idx_caf_patronato_scadenza (scadenza_at),
    FOREIGN KEY (cliente_id) REFERENCES clienti(id) ON DELETE SET NULL,
    FOREIGN KEY (appuntamento_id) REFERENCES servizi_appuntamenti(id) ON DELETE SET NULL,
    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
