-- Crea tabelle per la gestione dei telegrammi inviati tramite Ufficio Postale
CREATE TABLE IF NOT EXISTS servizi_telegrammi (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    telegramma_id VARCHAR(64) NOT NULL UNIQUE,
    cliente_id INT UNSIGNED NULL,
    riferimento VARCHAR(160) NULL,
    prodotto VARCHAR(80) NOT NULL DEFAULT 'telegramma',
    stato VARCHAR(40) NOT NULL DEFAULT 'NEW',
    substate VARCHAR(40) NULL,
    confirmed TINYINT(1) NOT NULL DEFAULT 0,
    creation_timestamp DATETIME NULL,
    update_timestamp DATETIME NULL,
    sending_timestamp DATETIME NULL,
    sent_timestamp DATETIME NULL,
    confirmed_timestamp DATETIME NULL,
    guid_utente VARCHAR(120) NULL,
    richiesta_id VARCHAR(120) NULL,
    last_error VARCHAR(255) NULL,
    last_error_timestamp DATETIME NULL,
    mittente_json LONGTEXT NULL,
    destinatari_json LONGTEXT NULL,
    documento_testo LONGTEXT NULL,
    opzioni_json LONGTEXT NULL,
    documento_validato_json LONGTEXT NULL,
    pricing_json LONGTEXT NULL,
    callback_json LONGTEXT NULL,
    raw_payload LONGTEXT NULL,
    note TEXT NULL,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_servizi_telegrammi_state (stato),
    INDEX idx_servizi_telegrammi_cliente (cliente_id),
    INDEX idx_servizi_telegrammi_created (created_at),
    CONSTRAINT fk_servizi_telegrammi_cliente FOREIGN KEY (cliente_id) REFERENCES clienti(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS servizi_telegrammi_log (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    servizi_telegrammi_id INT UNSIGNED NOT NULL,
    evento VARCHAR(80) NOT NULL,
    messaggio TEXT NULL,
    meta_json LONGTEXT NULL,
    created_by INT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_servizi_telegrammi_log (servizi_telegrammi_id),
    CONSTRAINT fk_servizi_telegrammi_log FOREIGN KEY (servizi_telegrammi_id) REFERENCES servizi_telegrammi(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
