CREATE TABLE IF NOT EXISTS brt_shipments (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    sender_customer_code VARCHAR(20) NOT NULL,
    numeric_sender_reference BIGINT UNSIGNED NOT NULL,
    alphanumeric_sender_reference VARCHAR(80) NOT NULL,
    departure_depot VARCHAR(10) NOT NULL,
    arrival_depot VARCHAR(10) NULL,
    arrival_terminal VARCHAR(10) NULL,
    parcel_number_from VARCHAR(30) NULL,
    parcel_number_to VARCHAR(30) NULL,
    parcel_id VARCHAR(40) NULL,
    number_of_parcels SMALLINT UNSIGNED NOT NULL DEFAULT 1,
    weight_kg DECIMAL(10,3) NOT NULL DEFAULT 0,
    volume_m3 DECIMAL(10,3) NOT NULL DEFAULT 0,
    consignee_name VARCHAR(180) NOT NULL,
    consignee_address VARCHAR(255) NOT NULL,
    consignee_zip VARCHAR(20) NOT NULL,
    consignee_city VARCHAR(150) NOT NULL,
    consignee_province VARCHAR(10) NULL,
    consignee_country VARCHAR(4) NULL,
    consignee_phone VARCHAR(40) NULL,
    consignee_email VARCHAR(160) NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'created',
    execution_code INT NOT NULL DEFAULT 0,
    execution_code_description VARCHAR(255) NULL,
    execution_message TEXT NULL,
    label_path VARCHAR(255) NULL,
    request_payload LONGTEXT NULL,
    response_payload LONGTEXT NULL,
    confirmed_at DATETIME NULL,
    deleted_at DATETIME NULL,
    last_tracking_payload LONGTEXT NULL,
    last_tracking_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_brt_shipment_reference (sender_customer_code, numeric_sender_reference),
    KEY idx_brt_shipment_parcel (parcel_id),
    KEY idx_brt_shipment_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS brt_orm_requests (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    reservation_number VARCHAR(60) NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'pending',
    collection_date DATE NULL,
    payer_type VARCHAR(20) NULL,
    parcels SMALLINT UNSIGNED NULL,
    weight_kg DECIMAL(10,3) NULL,
    request_payload LONGTEXT NOT NULL,
    response_payload LONGTEXT NULL,
    errors_payload LONGTEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_brt_orm_reservation (reservation_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
