CREATE TABLE IF NOT EXISTS certi_requests (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    tipo_certificato VARCHAR(120) NOT NULL,
    categoria ENUM('comunale','camerale','catastale') NOT NULL,
    dati_intestatario JSON NOT NULL,
    stato ENUM('nuova','in_validazione','in_lavorazione','in_attesa_api','completata','respinta','errore_api') NOT NULL DEFAULT 'nuova',
    urgenza ENUM('standard','prioritaria','urgentissima') NOT NULL DEFAULT 'standard',
    note_interne TEXT NULL,
    file_certificato VARCHAR(255) NULL,
    assegnato_a INT UNSIGNED NULL,
    ticket_id BIGINT UNSIGNED NULL,
    docuengine_request_id VARCHAR(120) NULL,
    visengine_request_id VARCHAR(120) NULL,
    catasto_request_id VARCHAR(120) NULL,
    completata_il DATETIME NULL,
    deleted_at DATETIME NULL,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_certi_requests_categoria (categoria),
    INDEX idx_certi_requests_stato (stato),
    INDEX idx_certi_requests_urgenza (urgenza),
    INDEX idx_certi_requests_assigned (assegnato_a),
    INDEX idx_certi_requests_ticket (ticket_id),
    INDEX idx_certi_requests_docuengine (docuengine_request_id),
    INDEX idx_certi_requests_visengine (visengine_request_id),
    INDEX idx_certi_requests_catasto (catasto_request_id),
    INDEX idx_certi_requests_created (created_at),
    CONSTRAINT fk_certi_requests_assigned FOREIGN KEY (assegnato_a) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_certi_requests_ticket FOREIGN KEY (ticket_id) REFERENCES tickets(id) ON DELETE SET NULL,
    CONSTRAINT fk_certi_requests_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT fk_certi_requests_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS certi_logs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    request_id BIGINT UNSIGNED NOT NULL,
    action VARCHAR(80) NOT NULL,
    actor_id INT UNSIGNED NULL,
    actor_name VARCHAR(190) NULL,
    details TEXT NULL,
    old_snapshot JSON NULL,
    new_snapshot JSON NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_certi_logs_request FOREIGN KEY (request_id) REFERENCES certi_requests(id) ON DELETE CASCADE,
    CONSTRAINT fk_certi_logs_actor FOREIGN KEY (actor_id) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_certi_logs_request_created (request_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS certi_api_logs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    request_id BIGINT UNSIGNED NULL,
    provider ENUM('docuengine','visengine','catasto') NOT NULL,
    endpoint VARCHAR(190) NOT NULL,
    payload JSON NULL,
    response JSON NULL,
    status_code INT NULL,
    success TINYINT(1) NOT NULL DEFAULT 0,
    error_message VARCHAR(255) NULL,
    retry_attempt TINYINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_certi_api_logs_request FOREIGN KEY (request_id) REFERENCES certi_requests(id) ON DELETE SET NULL,
    INDEX idx_certi_api_logs_request_created (request_id, created_at),
    INDEX idx_certi_api_logs_provider (provider)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
