CREATE TABLE IF NOT EXISTS servizi_web_progetti (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    codice VARCHAR(40) NOT NULL UNIQUE,
    cliente_id INT UNSIGNED NOT NULL,
    tipo_servizio ENUM('Sito vetrina','E-commerce','Branding e grafica','Domini e hosting','Servizi di stampa') NOT NULL,
    titolo VARCHAR(160) NOT NULL,
    descrizione TEXT NULL,
    include_domini TINYINT(1) NOT NULL DEFAULT 0,
    include_email_professionali TINYINT(1) NOT NULL DEFAULT 0,
    include_hosting TINYINT(1) NOT NULL DEFAULT 0,
    include_stampa TINYINT(1) NOT NULL DEFAULT 0,
    stato ENUM('preventivo','in_attesa_cliente','in_lavorazione','consegnato','annullato') NOT NULL DEFAULT 'preventivo',
    preventivo_numero VARCHAR(80) NULL,
    preventivo_importo DECIMAL(10,2) NULL,
    ordine_numero VARCHAR(80) NULL,
    ordine_importo DECIMAL(10,2) NULL,
    consegna_prevista DATE NULL,
    note_interne TEXT NULL,
    allegato_path VARCHAR(255) NULL,
    allegato_hash CHAR(64) NULL,
    allegato_caricato_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_web_cliente (cliente_id),
    INDEX idx_web_stato (stato),
    FOREIGN KEY (cliente_id) REFERENCES clienti(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
