CREATE TABLE IF NOT EXISTS anpr_pratiche (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    pratica_code VARCHAR(40) NOT NULL UNIQUE,
    cliente_id INT UNSIGNED NOT NULL,
    tipo_pratica VARCHAR(80) NOT NULL,
    stato ENUM('In lavorazione','Completato','Annullato') NOT NULL DEFAULT 'In lavorazione',
    note_interne TEXT NULL,
    certificato_path VARCHAR(255) NULL,
    certificato_hash CHAR(64) NULL,
    certificato_caricato_at DATETIME NULL,
    operatore_id INT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_anpr_cliente (cliente_id),
    INDEX idx_anpr_tipo (tipo_pratica),
    INDEX idx_anpr_stato (stato),
    INDEX idx_anpr_operatore (operatore_id),
    FOREIGN KEY (cliente_id) REFERENCES clienti(id) ON DELETE CASCADE,
    FOREIGN KEY (operatore_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
