ALTER TABLE servizi_aci_pratiche
    ADD persona_giuridica TINYINT(1) NOT NULL DEFAULT 0,
    ADD intestatario_nome VARCHAR(150) NULL,
    ADD intestatario_cognome VARCHAR(150) NULL,
    ADD intestatario_codice_fiscale VARCHAR(32) NULL,
    ADD intestatario_data_nascita DATE NULL,
    ADD intestatario_luogo_nascita VARCHAR(150) NULL,
    ADD intestatario_residenza TEXT NULL,
    ADD intestatario_email VARCHAR(190) NULL,
    ADD intestatario_telefono VARCHAR(30) NULL,
    ADD intestatario_ragione_sociale VARCHAR(190) NULL,
    ADD intestatario_partita_iva VARCHAR(32) NULL,
    ADD intestatario_codice_fiscale_giuridico VARCHAR(32) NULL,
    ADD intestatario_sede_legale TEXT NULL,
    ADD veicolo_tipo VARCHAR(40) NULL,
    ADD veicolo_marca VARCHAR(80) NULL,
    ADD veicolo_modello VARCHAR(80) NULL,
    ADD veicolo_anno_immatricolazione YEAR NULL,
    ADD veicolo_alimentazione VARCHAR(40) NULL,
    ADD veicolo_potenza_kw DECIMAL(8,2) NULL,
    ADD veicolo_classe_ambientale VARCHAR(40) NULL,
    ADD venditore_nome VARCHAR(190) NULL,
    ADD venditore_codice_fiscale VARCHAR(32) NULL,
    ADD venditore_indirizzo TEXT NULL,
    ADD acquirente_nome VARCHAR(190) NULL,
    ADD acquirente_codice_fiscale VARCHAR(32) NULL,
    ADD acquirente_indirizzo TEXT NULL,
    ADD venditore_acquirente_coincidono TINYINT(1) NOT NULL DEFAULT 0,
    ADD diritti_aci DECIMAL(10,2) NOT NULL DEFAULT 0,
    ADD imposta_bollo DECIMAL(10,2) NOT NULL DEFAULT 0,
    ADD emolumenti DECIMAL(10,2) NOT NULL DEFAULT 0,
    ADD compenso_agenzia DECIMAL(10,2) NOT NULL DEFAULT 0,
    ADD totale DECIMAL(10,2) NOT NULL DEFAULT 0,
    ADD metodo_pagamento VARCHAR(40) NULL,
    ADD consenso_privacy TINYINT(1) NOT NULL DEFAULT 0,
    ADD consenso_aci TINYINT(1) NOT NULL DEFAULT 0,
    ADD consenso_veridicita TINYINT(1) NOT NULL DEFAULT 0,
    ADD note_interne TEXT NULL,
    ADD tipo_pratica_altro VARCHAR(190) NULL,
    ADD assigned_to INT UNSIGNED NULL;

ALTER TABLE servizi_aci_allegati
    ADD categoria VARCHAR(50) NOT NULL DEFAULT 'generico';
