name: Deploy Coresuite Business

on:
  workflow_dispatch:
  push:
    branches: [main, production]

jobs:
  deploy-sftp:
    name: Hostinger SFTP
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_HOST }}
          port: 65002
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local_path: ./*
          remote_path: /${{ vars.FTP_SERVER_DIR }}
          sftp_only: true
          delete_remote_files: false
